name: Publish DataProtectionCrypto

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ["windows"]
        include:
          - kind: windows
            os: windows-latest
            target: win-x64
        dotnet-version: ["6.0.x"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="DataProtectionCrypto-$tag-${{ matrix.target }}"

          # Build everything
          dotnet publish src/DataProtectionCrypto/DataProtectionCrypto.csproj -c Release -o "$release_name" -r "${{ matrix.target }}" --no-self-contained

          # Pack files
          7z a -tzip "${release_name}.zip" "./${release_name}/*"

          # Delete output directory
          rm -r "$release_name"

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "DataProtectionCrypto*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
